const MODES={pomodoro:{minutes:25,label:'집중 시간',name:'집중',color:'#d9604f'},short:{minutes:5,label:'짧은 휴식',name:'짧은 휴식',color:'#648673'},long:{minutes:15,label:'긴 휴식',name:'긴 휴식',color:'#648673'}};
const $=selector=>document.querySelector(selector),storageKey='focusflow-sessions';
let mode='pomodoro',total=1500,remaining=1500,running=false,interval,sessionTask='';
function todayKey(){return new Date().toLocaleDateString('sv-SE')}
const sessions=JSON.parse(localStorage.getItem(storageKey)||'[]').filter(item=>item.date===todayKey()).map(item=>({...item,seconds:item.seconds??(item.minutes||0)*60}));
function displayDate(){return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}
function formatDuration(seconds){const minutes=Math.floor(seconds/60),remainder=seconds%60;return `${String(minutes).padStart(2,'0')}:${String(remainder).padStart(2,'0')}`}
function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}
function renderTimer(){const minutes=Math.floor(remaining/60),seconds=remaining%60;$('#time').textContent=formatDuration(remaining);$('#time').dateTime=`PT${minutes}M${seconds}S`;$('#dial-progress').style.strokeDashoffset=829.38*(1-remaining/total);$('#start-label').textContent=running?'일시정지':'시작하기';$('.play').textContent=running?'Ⅱ':'▶'}
function renderHistory(){const list=$('#session-list'),focusSeconds=sessions.filter(s=>s.mode==='pomodoro').reduce((sum,s)=>sum+s.seconds,0);$('#focus-total').textContent=Math.floor(focusSeconds/60);list.innerHTML=sessions.slice().reverse().map(s=>`<li class="session ${s.mode==='pomodoro'?'':'break'}"><span class="session-icon">${s.mode==='pomodoro'?'●':'☕'}</span><span class="session-detail"><span class="session-name">${escapeHtml(s.name)}</span>${s.task?`<span class="session-task">${escapeHtml(s.task)}</span>`:''}</span><span class="session-time">${formatDuration(s.seconds)} · ${s.time}</span></li>`).join('');const hasSessions=sessions.length>0;$('#empty-history').hidden=hasSessions;$('#clear-history').hidden=!hasSessions;$('#copy-history').hidden=!hasSessions}
function saveSession(){const seconds=total-remaining;if(seconds<1)return;const now=new Date();sessions.push({date:todayKey(),mode,name:MODES[mode].name,task:sessionTask,seconds,time:now.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})});localStorage.setItem(storageKey,JSON.stringify(sessions));renderHistory()}
function setMode(next){mode=next;total=remaining=MODES[mode].minutes*60;sessionTask='';running=false;clearInterval(interval);$('#mode-label').textContent=MODES[mode].label;$('#dial-progress').style.stroke=MODES[mode].color;document.querySelectorAll('.mode').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));renderTimer()}
function finish(){running=false;clearInterval(interval);saveSession();remaining=total;sessionTask='';document.title='focusflow — 세션 완료';renderTimer()}
function beginTimer(){running=true;interval=setInterval(()=>{if(remaining<=1){remaining=0;finish()}else{remaining--;renderTimer()}},1000);renderTimer()}
function startOrPause(){if(running){running=false;clearInterval(interval);renderTimer();return}if(mode==='pomodoro'&&!sessionTask){$('#task-input').value='';$('#task-dialog').showModal();setTimeout(()=>$('#task-input').focus(),0);return}beginTimer()}
function copyHistory(){const focusSeconds=sessions.filter(s=>s.mode==='pomodoro').reduce((sum,s)=>sum+s.seconds,0);const text=[`오늘의 집중 기록 (${displayDate()})`,`총 집중 시간: ${formatDuration(focusSeconds)}`,'',...sessions.map(s=>`- ${s.time} · ${s.name} ${formatDuration(s.seconds)}${s.task?` · ${s.task}`:''}`)].join('\n'),button=$('#copy-history'),done=()=>{const original=button.textContent;button.textContent='복사됨';setTimeout(()=>button.textContent=original,1500)},showCopy=()=>{$('#copy-text').value=text;$('#copy-dialog').showModal();setTimeout(()=>$('#copy-text').select(),0)};if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(done).catch(showCopy)}else showCopy()}
$('#start').onclick=startOrPause;$('#reset').onclick=()=>{running=false;clearInterval(interval);remaining=total;sessionTask='';renderTimer()};$('#skip').onclick=finish;document.querySelectorAll('.mode').forEach(button=>button.onclick=()=>setMode(button.dataset.mode));
$('#task-form').addEventListener('submit',event=>{event.preventDefault();if(event.submitter.value==='cancel'){$('#task-dialog').close();return}sessionTask=$('#task-input').value.trim()||'이름 없는 집중';$('#task-dialog').close();beginTimer()});$('#clear-history').onclick=()=>{sessions.length=0;localStorage.removeItem(storageKey);renderHistory()};$('#copy-history').onclick=copyHistory;$('#today').textContent=displayDate();renderTimer();renderHistory();
